package gamejam;

import java.util.ArrayList;

import com.mygdx.game.objects.GameObject;
import com.mygdx.game.scenes.GameScene;

public class Map {

	public ArrayList<GameObject> mapObjects;
	
	public Map(GameScene scene) {
		mapObjects = new ArrayList<GameObject>();
		set1(scene);
		for(int i = 0; i < mapObjects.size(); i++)
		scene.addGameObject(mapObjects.get(i));
	}
	
	void set1(GameScene scene) {
		

		Sprajty plansza = new Sprajty();
		plansza.set(1, 0, 0);
		mapObjects.add(plansza);
		Mebl sciana1 = new Mebl(scene.getWorld(), 0, 1485, MebleId.sciana);
		mapObjects.add(sciana1);
		Mebl sciana2 = new Mebl(scene.getWorld(), 0, -1485, MebleId.sciana);
		mapObjects.add(sciana2);
		Mebl sciana3 = new Mebl(scene.getWorld(), 1985, 0, MebleId.sciana2);
		mapObjects.add(sciana3);
		Mebl sciana4 = new Mebl(scene.getWorld(), -1985, 0, MebleId.sciana2);
		mapObjects.add(sciana4);
		Mebl sciana5 = new Mebl(scene.getWorld(), -1025, -1250, MebleId.scianapion);
		mapObjects.add(sciana5);
		Mebl sciana6 = new Mebl(scene.getWorld(), -1025, -650, MebleId.scianapion);
		mapObjects.add(sciana6);
		Mebl sciana7 = new Mebl(scene.getWorld(), -1225, -500, MebleId.scianapoziom);
		mapObjects.add(sciana7);
		Mebl sciana8 = new Mebl(scene.getWorld(), -1625, -500, MebleId.scianapoziom);
		mapObjects.add(sciana8);
		Mebl sciana9 = new Mebl(scene.getWorld(), -1800, -500, MebleId.scianapoziom);
		mapObjects.add(sciana9);
		Mebl pufa = new Mebl(scene.getWorld(), 300, 350, MebleId.pufa);
		mapObjects.add(pufa);
		Mebl banany = new Mebl(scene.getWorld(), 700, 700, MebleId.banany);
		mapObjects.add(banany);
		Mebl pizza = new Mebl(scene.getWorld(), 700, 200, MebleId.pizza);
		mapObjects.add(pizza);
		Mebl tronpokuj = new Mebl(scene.getWorld(), -1700, -675, MebleId.tron);
		mapObjects.add(tronpokuj);
		Mebl pizzapokuj = new Mebl(scene.getWorld(), -1400, -650, MebleId.pizza);
		mapObjects.add(pizzapokuj);
		Mebl bananypokuj = new Mebl(scene.getWorld(), -1850, -1350, MebleId.banany);
		mapObjects.add(bananypokuj);
		Mebl bananypokuj2 = new Mebl(scene.getWorld(), -1750, -1350, MebleId.banany);
		mapObjects.add(bananypokuj2);
		Mebl bananypokuj3 = new Mebl(scene.getWorld(), -1650, -1350, MebleId.banany);
		mapObjects.add(bananypokuj3);
		Mebl bananypokuj4 = new Mebl(scene.getWorld(), -1550, -1350, MebleId.banany);
		mapObjects.add(bananypokuj4);
		Mebl bananypokuj5 = new Mebl(scene.getWorld(), -1450, -1350, MebleId.banany);
		mapObjects.add(bananypokuj5);
		Mebl fotelpokuj = new Mebl(scene.getWorld(), -1250, -650, MebleId.fotel2);
		mapObjects.add(fotelpokuj);
		Mebl pufazarciepokuj = new Mebl(scene.getWorld(), -1570, -825, MebleId.pufajedzenie);
		mapObjects.add(pufazarciepokuj);
		Mebl subpokuj = new Mebl(scene.getWorld(), -1350,-1350 , MebleId.subway);
		mapObjects.add(subpokuj);
		Mebl subpokuj2 = new Mebl(scene.getWorld(), -1310,-1350 , MebleId.subway);
		mapObjects.add(subpokuj2);
		Mebl subpokuj3 = new Mebl(scene.getWorld(), -1270,-1350 , MebleId.subway);
		mapObjects.add(subpokuj3);
		Mebl subpokuj4 = new Mebl(scene.getWorld(), -1230,-1350 , MebleId.subway);
		mapObjects.add(subpokuj4);
		Mebl subpokuj5 = new Mebl(scene.getWorld(), -1190,-1350 , MebleId.subway);
		mapObjects.add(subpokuj5);
		Mebl subpokuj6 = new Mebl(scene.getWorld(), -1350,-1294 , MebleId.subway);
		mapObjects.add(subpokuj6);
		Mebl subpokuj7 = new Mebl(scene.getWorld(), -1310,-1294 , MebleId.subway);
		mapObjects.add(subpokuj7);
		Mebl subpokuj8 = new Mebl(scene.getWorld(), -1270,-1294 , MebleId.subway);
		mapObjects.add(subpokuj8);
		Mebl subpokuj9 = new Mebl(scene.getWorld(), -1230,-1294 , MebleId.subway);
		mapObjects.add(subpokuj9);
		Mebl subpokuj10 = new Mebl(scene.getWorld(), -1190,-1294 , MebleId.subway);
		mapObjects.add(subpokuj10);
		Mebl subpokuj11 = new Mebl(scene.getWorld(), -1350,-1238 , MebleId.subway);
		mapObjects.add(subpokuj11);
		Mebl subpokuj12 = new Mebl(scene.getWorld(), -1310,-1238 , MebleId.subway);
		mapObjects.add(subpokuj12);
		Mebl subpokuj13 = new Mebl(scene.getWorld(), -1270,-1238 , MebleId.subway);
		mapObjects.add(subpokuj13);
		Mebl subpokuj14 = new Mebl(scene.getWorld(), -1230,-1238 , MebleId.subway);
		mapObjects.add(subpokuj14);
		Mebl subpokuj15 = new Mebl(scene.getWorld(), -1190,-1238 , MebleId.subway);
		mapObjects.add(subpokuj15);
		Mebl subpokuj16 = new Mebl(scene.getWorld(), -1350,-1182 , MebleId.subway);
		mapObjects.add(subpokuj16);
		Mebl subpokuj17 = new Mebl(scene.getWorld(), -1310,-1182 , MebleId.subway);
		mapObjects.add(subpokuj17);
		Mebl subpokuj18 = new Mebl(scene.getWorld(), -1270,-1182 , MebleId.subway);
		mapObjects.add(subpokuj18);
		Mebl subpokuj19 = new Mebl(scene.getWorld(), -1230,-1182 , MebleId.subway);
		mapObjects.add(subpokuj19);
		Mebl subpokuj20 = new Mebl(scene.getWorld(), -1190,-1182 , MebleId.subway);
		mapObjects.add(subpokuj20);
		Mebl subpokuj21 = new Mebl(scene.getWorld(), -1350,-1126 , MebleId.subway);
		mapObjects.add(subpokuj21);
		Mebl subpokuj22 = new Mebl(scene.getWorld(), -1310,-1126 , MebleId.subway);
		mapObjects.add(subpokuj22);
		Mebl subpokuj23 = new Mebl(scene.getWorld(), -1270,-1126 , MebleId.subway);
		mapObjects.add(subpokuj23);
		Mebl subpokuj24 = new Mebl(scene.getWorld(), -1230,-1126 , MebleId.subway);
		mapObjects.add(subpokuj24);
		Mebl subpokuj25 = new Mebl(scene.getWorld(), -1190,-1126 , MebleId.subway);
		mapObjects.add(subpokuj25);
		Mebl kaloryferpokuj = new Mebl(scene.getWorld(), -960, -1250, MebleId.kaloryferpion);
		mapObjects.add(kaloryferpokuj);
		Mebl krzeslo = new Mebl(scene.getWorld(), -1200, 950, MebleId.krzeslo);
		mapObjects.add(krzeslo);
		Mebl krzeslo2 = new Mebl(scene.getWorld(),-280, 950, MebleId.krzeslo);
		mapObjects.add(krzeslo2);
		Mebl krzeslo3 = new Mebl(scene.getWorld(), -500, 650, MebleId.krzeslo2);
		mapObjects.add(krzeslo3);
		Mebl krzeslo4 = new Mebl(scene.getWorld(), -280, 650, MebleId.krzeslo2);
		mapObjects.add(krzeslo4);
		
		Mebl pufa2 = new Mebl(scene.getWorld(), 400, 1000, MebleId.pufajedzenie);
		mapObjects.add(pufa2);
		Mebl stolek = new Mebl(scene.getWorld(), 800, 600, MebleId.stolek);
		mapObjects.add(stolek);
		Mebl stolek2 = new Mebl(scene.getWorld(), -1000, 950, MebleId.stolek);
		mapObjects.add(stolek2);
		Mebl stolek3 = new Mebl(scene.getWorld(), -500, 950, MebleId.stolek);
		mapObjects.add(stolek3);
		Mebl stolek4 = new Mebl(scene.getWorld(), -1000, 650, MebleId.stolek);
		mapObjects.add(stolek4);
		Mebl stolek5 = new Mebl(scene.getWorld(), -1200, 650, MebleId.stolek);
		mapObjects.add(stolek5);
		Mebl szafka = new Mebl(scene.getWorld(), 1000, 1000, MebleId.szafka);
		mapObjects.add(szafka);
		Mebl szafka2 = new Mebl(scene.getWorld(), 1000, 1178, MebleId.szafka);
		mapObjects.add(szafka2);
		Mebl filarszfka = new Mebl(scene.getWorld(), 875, 986, MebleId.filar);
		mapObjects.add(filarszfka);
		Mebl pufa3 = new Mebl(scene.getWorld(), 1000, 500, MebleId.pufa_mala);
		mapObjects.add(pufa3);
		Mebl kaloryfer = new Mebl(scene.getWorld(), 900, -1435, MebleId.kaloryfer);
		mapObjects.add(kaloryfer);
		Mebl tron = new Mebl(scene.getWorld(), 1450, 1000, MebleId.tron);
		mapObjects.add(tron);
		Mebl stolrog = new Mebl(scene.getWorld(), 1700, 1150, MebleId.stolpion);
		mapObjects.add(stolrog);
		Mebl pufastol = new Mebl(scene.getWorld(), 1450, 1250, MebleId.pufa);
		mapObjects.add(pufastol);
		Mebl fotel = new Mebl(scene.getWorld(), 600, -600, MebleId.fotel);
		mapObjects.add(fotel);
		Mebl filar1 = new Mebl(scene.getWorld(), -300, -300, MebleId.filar);
		mapObjects.add(filar1);
		Mebl filar2 = new Mebl(scene.getWorld(), -300, 300, MebleId.filar);
		mapObjects.add(filar2);
		Mebl filar3 = new Mebl(scene.getWorld(), 300, -300, MebleId.filar);
		mapObjects.add(filar3);
		Mebl filar4 = new Mebl(scene.getWorld(), 300, 300, MebleId.filar);
		mapObjects.add(filar4);
		Mebl filar5 = new Mebl(scene.getWorld(), 100, -1200, MebleId.filar);
		mapObjects.add(filar5);
		Mebl filar6 = new Mebl(scene.getWorld(), 1200, -1200, MebleId.filar);
		mapObjects.add(filar6);
		Mebl kanapa = new Mebl(scene.getWorld(), 650, -1200, MebleId.kanapa);
		mapObjects.add(kanapa);
		Mebl fotelkulka = new Mebl(scene.getWorld(), 800, 350, MebleId.fotelkulka);
		mapObjects.add(fotelkulka);
		Mebl wiktor2 = new Mebl(scene.getWorld(), 0, -300, MebleId.wiktor);
		mapObjects.add(wiktor2);
		Mebl wojtas2 = new Mebl(scene.getWorld(), -300, 0, MebleId.wojtas);
		mapObjects.add(wojtas2);
		Mebl stefan2 = new Mebl(scene.getWorld(), 0, 300, MebleId.stefan);
		mapObjects.add(stefan2);
		Mebl sub = new Mebl(scene.getWorld(), -900,900 , MebleId.subway);
		mapObjects.add(sub);
		Mebl sub2 = new Mebl(scene.getWorld(), -860,900 , MebleId.subway);
		mapObjects.add(sub2);
		Mebl sub3 = new Mebl(scene.getWorld(), -820,900 , MebleId.subway);
		mapObjects.add(sub3);
		Mebl sub4 = new Mebl(scene.getWorld(), -780,900 , MebleId.subway);
		mapObjects.add(sub4);
		Mebl sub5 = new Mebl(scene.getWorld(), -740,900 , MebleId.subway);
		mapObjects.add(sub5);
		Mebl sub6 = new Mebl(scene.getWorld(), -700,900 , MebleId.subway);
		mapObjects.add(sub6);
		Mebl sub7 = new Mebl(scene.getWorld(), -900,844 , MebleId.subway);
		mapObjects.add(sub7);
		Mebl sub8 = new Mebl(scene.getWorld(), -860,844 , MebleId.subway);
		mapObjects.add(sub8);
		Mebl sub9 = new Mebl(scene.getWorld(), -820,844 , MebleId.subway);
		mapObjects.add(sub9);
		Mebl sub10 = new Mebl(scene.getWorld(), -780,844 , MebleId.subway);
		mapObjects.add(sub10);
		Mebl sub11 = new Mebl(scene.getWorld(), -740,844 , MebleId.subway);
		mapObjects.add(sub11);
		Mebl sub12 = new Mebl(scene.getWorld(), -700,844 , MebleId.subway);
		mapObjects.add(sub12);
		Mebl sub13 = new Mebl(scene.getWorld(), -900,788 , MebleId.subway);
		mapObjects.add(sub13);
		Mebl sub14 = new Mebl(scene.getWorld(), -860,788 , MebleId.subway);
		mapObjects.add(sub14);
		Mebl sub15 = new Mebl(scene.getWorld(), -820,788 , MebleId.subway);
		mapObjects.add(sub15);
		Mebl sub16 = new Mebl(scene.getWorld(), -780,788 , MebleId.subway);
		mapObjects.add(sub16);
		Mebl sub17 = new Mebl(scene.getWorld(), -740,788 , MebleId.subway);
		mapObjects.add(sub17);
		Mebl sub18 = new Mebl(scene.getWorld(), -700,788 , MebleId.subway);
		mapObjects.add(sub18);
		Mebl sub19 = new Mebl(scene.getWorld(), -900,732 , MebleId.subway);
		mapObjects.add(sub19);
		Mebl sub20 = new Mebl(scene.getWorld(), -860,732 , MebleId.subway);
		mapObjects.add(sub20);
		Mebl sub21 = new Mebl(scene.getWorld(), -820,732 , MebleId.subway);
		mapObjects.add(sub21);
		Mebl sub22 = new Mebl(scene.getWorld(), -780,732 , MebleId.subway);
		mapObjects.add(sub22);
		Mebl sub23 = new Mebl(scene.getWorld(), -740,732 , MebleId.subway);
		mapObjects.add(sub23);
		Mebl sub24 = new Mebl(scene.getWorld(), -700,732 , MebleId.subway);
		mapObjects.add(sub24);
		Mebl stol = new Mebl(scene.getWorld(), -400,800 , MebleId.stol);
		mapObjects.add(stol);
		Mebl stol2 = new Mebl(scene.getWorld(), -1100,800 , MebleId.stol2);
		mapObjects.add(stol2);
		Mebl stolpd = new Mebl(scene.getWorld(), 1750,-600 , MebleId.stol2);
		mapObjects.add(stolpd);
		Mebl scianpd = new Mebl(scene.getWorld(), 1750,-400 , MebleId.scianapoziom);
		mapObjects.add(scianpd);
		Mebl scianpd2 = new Mebl(scene.getWorld(), 1350,-400 , MebleId.scianapoziom);
		mapObjects.add(scianpd2);
		Mebl subrand1 = new Mebl(scene.getWorld(), 1453,-324 , MebleId.subway);
		mapObjects.add(subrand1);
		Mebl subrand2 = new Mebl(scene.getWorld(), 1123,-824 , MebleId.subway);
		mapObjects.add(subrand2);
		Mebl subrand3 = new Mebl(scene.getWorld(), -1123,82 , MebleId.subway);
		mapObjects.add(subrand3);
		Mebl bananyfilar = new Mebl(scene.getWorld(), -1200, -100, MebleId.banany);
		mapObjects.add(bananyfilar);
		Mebl bananyfilar2 = new Mebl(scene.getWorld(), -1300, -100, MebleId.banany);
		mapObjects.add(bananyfilar2);
		Mebl bananyfilar3 = new Mebl(scene.getWorld(), -1200, 20, MebleId.banany);
		mapObjects.add(bananyfilar3);
		Mebl bananyfilar4 = new Mebl(scene.getWorld(), -1300, 20, MebleId.banany);
		mapObjects.add(bananyfilar4);
		Mebl tronpd = new Mebl(scene.getWorld(), 1400, -1200, MebleId.tron);
		mapObjects.add(tronpd);
		Mebl bananypd = new Mebl(scene.getWorld(), 1600, -1000, MebleId.banany);
		mapObjects.add(bananypd);
		Mebl bananypd2 = new Mebl(scene.getWorld(), 1500, -1000, MebleId.banany);
		mapObjects.add(bananypd2);
		Mebl bananypd3 = new Mebl(scene.getWorld(), 1700, -1000, MebleId.banany);
		mapObjects.add(bananypd3);
		Mebl fotelksp = new Mebl(scene.getWorld(), 1750, -200, MebleId.fotelkulka);
		mapObjects.add(fotelksp);
		Mebl fotelksp2 = new Mebl(scene.getWorld(), 1620, -200, MebleId.fotelkulka);
		mapObjects.add(fotelksp2);
		Mebl fotelksp3 = new Mebl(scene.getWorld(), 1750, -60, MebleId.fotelkulka);
		mapObjects.add(fotelksp3);
		Mebl scinasp = new Mebl(scene.getWorld(), 1250, 400, MebleId.scianapion);
		mapObjects.add(scinasp);
		Mebl scinasp2 = new Mebl(scene.getWorld(), 1250, 200, MebleId.scianapion);
		mapObjects.add(scinasp2);
		Mebl pizzals = new Mebl(scene.getWorld(), -1700, 300, MebleId.pizza);
		mapObjects.add(pizzals);
		Mebl pizzals2 = new Mebl(scene.getWorld(), -1700, 100, MebleId.pizza);
		mapObjects.add(pizzals2);
		Mebl pizzals3 = new Mebl(scene.getWorld(), -1700, -100, MebleId.pizza);
		mapObjects.add(pizzals3);
		Mebl klapek = new Mebl(scene.getWorld(), -600, -1000, MebleId.szafka);
		mapObjects.add(klapek);
		Mebl klapek2 = new Mebl(scene.getWorld(), -600, -1178, MebleId.szafka);
		mapObjects.add(klapek2);
		Mebl klapek3 = new Mebl(scene.getWorld(), -600, -822, MebleId.szafka);
		mapObjects.add(klapek3);
		
		//Mebl asd = new Mebl(scene.getWorld(), 200, 200, 1);
		//mapObjects.add(asd);

	}
}
